version: 2.1

orbs:
  docker: circleci/docker@0.5.13

workflows:
  build-and-publish-docker-image:
    jobs:
      - docker/publish:
          dockerfile: Dockerfile
          image: ooocamel/hello-gitops
          path: .